name: CI

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker://philkohn/academic-writing
      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: output/output.pdf application/pdf
