name: CI

on: release

jobs:
  build-pdf-release:
    name: Build and upload pdf from markdown.
    runs-on: ubuntu-latest
    steps:
      - name: pull source
        uses: actions/checkout@v3

      - name: Run Docker container to compile pdf
        uses: addnab/docker-run-action@v3
        with:
          image: pandoc/core:latest
          options: -v ${{ github.workspace }}:/data \
                  --user $(id -u):$(id -g)
          run: pandoc/core --filter pandoc-crossref --filter pandoc-citeproc \
              -M cref=true \
              --bibliography src/bibtex.bib --biblatex \
              --top-level-division=chapter \
              README.md -o output.pdf

      - uses: JasonEtco/upload-to-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: output.pdf application/pdf
          