name: compile pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container: 
      image: pandoc/latex:latest

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4

      - name: install python
        run: |
          apk update && apk add python3.8 python3-pip -y && ln -s /usr/bin/python3 /usr/bin/python

      - name: get xnos
        run: pip install pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos --user

      # run pandoc to generate pdf from markdown
      - name: run pandoc
        run: |
          pandoc --verbose --filter pandoc-xnos --citeproc "./src/input.md" --bibliography "./src/assets/bibtex.bib" --csl "./src/template/apa.csl" -o "output.pdf" --template "./src/template/imperial.tex"

      # output generated file to build artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: "output.pdf"